ALTER TABLE users ADD COLUMN IF NOT EXISTS is_staff BOOLEAN;

UPDATE users
SET is_staff = FALSE
WHERE is_staff IS NULL;

ALTER TABLE users ALTER COLUMN is_staff SET DEFAULT FALSE;
ALTER TABLE users ALTER COLUMN is_staff SET NOT NULL;
