ALTER TABLE users ADD COLUMN IF NOT EXISTS role INTEGER;
UPDATE users SET role = CASE WHEN COALESCE(is_staff, FALSE) THEN 2 ELSE 1 END WHERE role IS NULL;
ALTER TABLE users ALTER COLUMN role SET DEFAULT 1;
ALTER TABLE users ALTER COLUMN role SET NOT NULL;

ALTER TABLE appointments ADD COLUMN IF NOT EXISTS status VARCHAR(20);
UPDATE appointments SET status = 'PROCESSING' WHERE status IS NULL;
ALTER TABLE appointments ALTER COLUMN status SET DEFAULT 'PROCESSING';
ALTER TABLE appointments ALTER COLUMN status SET NOT NULL;

CREATE TABLE IF NOT EXISTS notifications (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    message VARCHAR(255) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_notifications_user_id_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);